//! Painel administrativo (rotas protegidas). A autorização é SEMPRE verificada
//! no servidor (sessão + RBAC); a UI aqui é apresentação, não controle de acesso.
mod configuracoes;
mod conteudo;
mod conteudo_sobre;
mod dashboard;
mod editor_pares;
mod em_construcao;
mod evento_form;
mod eventos;
mod layout;
mod leads;
mod login;
mod modal;
mod modal_categorias;
mod parceiro_form;
mod parceiros;
mod produto_form;
mod produtos;
mod recuperar;
mod redefinir;
mod upload_card;
mod usuario_form;
mod usuarios;
mod util;

pub use configuracoes::AdminConfiguracoes;
pub use conteudo::AdminConteudoHome;
pub use conteudo_sobre::AdminConteudoQuemSomos;
pub use dashboard::AdminDashboard;
pub use em_construcao::AdminEmBreve;
pub use evento_form::AdminEventoForm;
pub use eventos::AdminEventos;
pub use layout::AdminLayout;
pub use leads::AdminLeads;
pub use login::AdminLoginPage;
pub use parceiro_form::AdminParceiroForm;
pub use parceiros::AdminParceiros;
pub use produto_form::AdminProdutoForm;
pub use produtos::AdminProdutos;
pub use recuperar::AdminRecuperarSenhaPage;
pub use redefinir::AdminRedefinirSenhaPage;
pub use usuario_form::AdminUsuarioForm;
pub use usuarios::AdminUsuarios;
